README.md
docker-compose-test.yaml
docker-configuration-update.sh
nginx/conf.d-test/default.conf

Add test build from  main branches at port 8000
Issue [#27](https://github.com/Gamify-IT/issues/issues/27)

add test build

---

README.md
docker-compose-test.yaml
docker-compose.yml
nginx/conf.d-test/default.conf
nginx/conf.d/default.conf

Merge after Gamify-IT/lecturer-interface#3 is merged

Add lecturer interface to docker-compose and nginx configurations

---

README.md
docker-compose-test.yaml
nginx/conf.d-test/default.conf

add moorhuhn, crosswordpuzzle and overworld backend

---

nginx/conf.d-test/default.conf

part of  https://github.com/Gamify-IT/issues/issues/166

change test api paths to match ADR

---

nginx/conf.d-test/default.conf

part of https://github.com/Gamify-IT/issues/issues/166

change test api paths to match new definition

---

nginx/conf.d/default.conf

Closes https://github.com/Gamify-IT/issues/issues/166
Only merge after releases are created in all services

change production api paths

---

docker-compose-test.yaml
docker-compose.yml
nginx/conf.d-test/default.conf
nginx/conf.d/default.conf

change git card game internal port to 80 to match https://github.com/Gamify-IT/git-card-game/pull/7

change git card game internal port

---

README.md
docker-compose-test.yaml
docker-compose.yml
nginx/conf.d-test/default.conf
nginx/conf.d/default.conf

change moorhuhn to chickenshock to avoid legal problems

---

docker-compose-test.yaml
docker-compose.yml
nginx/conf.d-test/default.conf
nginx/conf.d/default.conf

add keycloak and FiniteQuiz.
Part of Gamify-IT/issues#252

add new services

---

docker-compose-test.yaml
docker-compose.yml

add keycloak issuer env to backends

---

docker-compose-test.yaml
docker-compose.yml

add keycloak url to backends

---

nginx/conf.d-test/default.conf
nginx/conf.d/default.conf

adjust proxy buffer size to allow keycloak register

---

goulburn/docker-compose-test.yaml
goulburn/docker-compose.yaml
template/docker-compose.yaml
testing/.env
testing/README.md
testing/docker-compose-latest.yaml
testing/docker-compose-main.yaml
testing/nginx/conf.d/default.conf

This PR adds a testing version of the run-config which allows an easy start of all containers with thest data.
To test this PR please start the docker-compose files and test if the all service are there.

add testing configuration

---

goulburn/dev/docker-compose.yaml

add overworld development  container to the development stage on goulburn

add overworld development stage

---

goulburn/dev/docker-compose.yaml
goulburn/prod/docker-compose.yaml
goulburn/test/docker-compose.yaml

This PR adds the development containers to the dev stage.
Part of Gamify-IT/issues#453

change containers to development on dev stage

---

template/docker/docker-compose-default.yaml

fix problem that all generated compose files have the same internal name

add name to compose

---

create-deployment.sh

Please test by creating a kubernetes deployment
```bash
./create-deployment.sh --kubernetes
```

correct deletion of kubernetes network-policy

---

template/docker/docker-compose-default.yaml
template/docker/docker-compose-fileserver.yaml

Implemented the previously temporary fixes, so that the shell script yields the right docker compose file.

Excluded fileserver, set ssl to false

---

README.md
create-deployment.sh

- Extended run config script to automatically start the containers
- Extended Readme to provide better usage information

Task update readme

---

README.md
create-deployment.sh
template/docker/docker-compose-template-services.yaml
template/docker/docker-compose-test-data.yaml

Enabled test data, extended readme with usage information

Enabled test data

---

README.md
helm chart/gamify-it-helm-config/.helmignore
helm chart/gamify-it-helm-config/Chart.yaml
helm chart/gamify-it-helm-config/templates/NOTES.txt
helm chart/gamify-it-helm-config/templates/_helpers.tpl
helm chart/gamify-it-helm-config/templates/backend-deployment.yaml
helm chart/gamify-it-helm-config/templates/frontend-deployment.yaml
helm chart/gamify-it-helm-config/templates/hpa.yaml
helm chart/gamify-it-helm-config/templates/ingress.yaml
helm chart/gamify-it-helm-config/templates/reverse-proxy-deployment.yaml
helm chart/gamify-it-helm-config/templates/reverse-proxy-service.yaml
helm chart/gamify-it-helm-config/templates/services.yaml
helm chart/gamify-it-helm-config/templates/statefulset.yaml
helm chart/gamify-it-helm-config/values.yaml
helm chart/keycloak-admin-secret.yaml
helm chart/pv.yaml

The helm chart folder contains the helm chart files and the pv.yaml file and keycloak-admin-secrets.yaml file, which must be applied before the helm chart.

Add helm chart folder

---

create_releases.sh
template/docker/docker-compose-default.yaml

Rename multiplayer-server to multiplayer-backend

Rename to multiplayer-backend
